[package]
name = "unicode-path-gen"
version = "0.1.0"
authors = ["Mark LeMoine <thatsgobbles@gmail.com>"]
edition = "2018"

[dependencies]
cursive = { version = "0.12", default-features = false, features = ["termion-backend"] }
strum = "0.17.1"
strum_macros = "0.17.1"
